### ISSUE TITLE
DNS doesn't work in registry URL - and I'm really sad because of that :(

### ISSUE THREAD

**Issue by Cloufish** [ChrisMacNaughton/cargo-cacher#21]
Hello Chris
Hope you're doing well
In case you ask me - I don't feel good like you

...That's because your great cargo-cacher doesn't work when I point to `http://localhost:8080/index`
_**However, It works when** referring to `http://127.0.0.1:8080/index`_

I get the following error
```bash
error:  Downloading crates ...
warning: spurious network error (2 tries remaining): [7] Couldn't connect to server (Failed to connect to localhost port 8080 after 1 ms: Couldn't connect to server)
```

But I do however want to put this application on a remote server and have a DNS  to `cargo-cacher.local`

I also tried to build other people's forks of this repo and use it, but the result is the same

Here's also full .cargo/config.toml: (even though It's the same as in your example)
```toml
[source]

[source.mirror]
registry = "http://localhost:8080/index"

[source.crates-io]
replace-with = "mirror"
```

I'll be commenting on this issue If I discover anything
